theme: jekyll-theme-slate
title: Nitinol Design Concepts
description: Design, simulation, and analysis resources from Confluent Medical Technologies
show_downloads: TRUE
google_analytics: UA-10953535-3
